<?php
/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2016 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<?php if ($this->isLegacyAccount()): ?>
<div class="notification-global">
    <strong><?php echo $this->helper('amazonpayments')->__('Amazon Pay and Login with Amazon'); ?></strong>:
    <?php echo $this->helper('amazonpayments')->__('From the next version of the extension, your shop needs to have a valid SSL certificate and you need to configure a Login with Amazon application in <a href="%s" target="_blank">Seller Central</a>', 'https://sellercentral-europe.amazon.com/hz/me/integration/details') ?>
</div>
<?php endif; ?>
