<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php /** @var Creativestyle_AmazonPayments_Block_Onepage_Button $this */ ?>
<div class="pay-with-amazon-onepage-shortcut">
    <h3><?php echo $this->__('Amazon Pay'); ?></h3>
    <?php // @codingStandardsIgnoreStart ?>
    <?php if ($this->isQuoteVirtual()): ?>
        <p><?php echo $this->__('<strong>Amazon Pay</strong> helps you shop quickly, safely and securely. You can pay on our website without re-entering your payment and address details.'); ?></p>
    <?php else: ?>
        <p><?php echo $this->__('<strong>Amazon Pay</strong> helps you shop quickly, safely and securely. You can pay on our website without re-entering your payment and address details. All Amazon transactions are protected by Amazon&apos;s A-to-z Guarantee.'); ?></p>
    <?php endif; ?>
    <?php // @codingStandardsIgnoreEnd ?>
    <?php echo $this->getChildHtml('amazonpayments_button_pay'); ?>
</div>
