<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php /** @var Creativestyle_AmazonPayments_Block_Js $this */ ?>
<?php if ($this->isOnePageCheckout()) : ?>
<?php
    $continueLabel = $this->helper('core')->quoteEscape($this->helper('checkout')->__('Continue'));
    $loadingNextStepLabel = $this->helper('core')->quoteEscape($this->__('Please wait, loading...'));
    $ajaxLoaderImgUrl = $this->getSkinUrl('images/opc-ajax-loader.gif');
?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('creativestyle/js/opcheckout_lpa.js'); ?>"></script>
    <script type="text/javascript">
        AmazonPaymentsOPC.init(checkout, billing, shipping, shippingMethod, payment, {
            live: <?php echo $this->isSandboxActive() ? 'false' : 'true' ?>,
            formKey: '<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>',
            continueButtonLabel: '<?php echo $continueLabel; ?>',
            pleaseWait: '<img src="<?php echo $ajaxLoaderImgUrl; ?>" alt="<?php echo $loadingNextStepLabel; ?>" title="<?php echo $loadingNextStepLabel; ?>" class="v-middle" /> <?php echo $loadingNextStepLabel; ?>'
        });
    </script>
<?php endif; ?>
<script type="text/javascript" src="<?php echo $this->getAppJsUrl(); ?>"></script>
<script type="text/javascript">
    AmazonPayments.setup(<?php echo $this->getJsConfig(); ?>);

    window.onAmazonPaymentsReady = function() {
        AmazonPayments
            .renderButtons()
<?php if ($this->getIsCheckout()) : ?>
<?php $orderReferenceId = $this->getOrderReferenceId(); ?>
<?php $accessToken = $this->getAccessToken(); ?>
<?php if ($orderReferenceId) : ?>
            .setOrderReferenceId('<?php echo $orderReferenceId; ?>')
<?php endif; ?>
<?php if ($accessToken) : ?>
            .setAccessToken('<?php echo $accessToken; ?>')
<?php endif; ?>
            .initCheckout({
                responsive: true,
                urls: <?php echo $this->getCheckoutUrls(); ?>

            })
<?php endif; ?>

<?php if ($this->getIsPayment()) : ?>
<?php $orderReferenceId = $this->getOrderReferenceId(); ?>
<?php if ($orderReferenceId) : ?>
            .setOrderReferenceId('<?php echo $orderReferenceId; ?>')
<?php endif; ?>
            .invalidPayment({
                urls: <?php echo $this->getCheckoutUrls(); ?>

            })
<?php endif; ?>

<?php if ($this->isOnePageCheckout()) : ?>
            .initOnepageCheckout({
                responsive: true,
                urls: <?php echo $this->getCheckoutUrls(); ?>
            })
<?php endif; ?>
        ;
    };

<?php if ($this->isLoginActive()) : ?>
    window.onAmazonLoginReady = function() {
        AmazonPayments
            .initLogin()
<?php if ($this->getIsLogout()) : ?>
            .logout()
<?php endif; ?>
        ;
    };
<?php endif; ?>
</script>
<script async type="text/javascript" src="<?php echo $this->getWidgetJsUrl(); ?>"></script>
