<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2015 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2015 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php /** @var Creativestyle_AmazonPayments_Block_Login_Redirect $this */?>
<h1><?php echo $this->__('Redirecting, please wait...'); ?></h1>
<script type="text/javascript">//<![CDATA[
    var accessToken = (new RegExp('[?|&|#]<?php echo $this->getAccessTokenParamName(); ?>=([^&;]+?)(&|#|;|$)')
        .exec(location.hash) || [,""])[1].replace(/\+/g,'%20') || null;
    var state = (new RegExp('[?|&|#]<?php echo $this->getStateParamName(); ?>=([^&;]+?)(&|#|;|$)').exec(location.hash) || [,""])[1] || null;
    if (typeof accessToken === 'string' && accessToken.match(/^Atza/)) {
        Mage.Cookies.set('amazon_Login_accessToken', decodeURIComponent(accessToken), null, '/', null, true);
        window.location.href = '<?php echo $this->getRedirectUrl(); ?>'
            .replace(/%access_token/, accessToken)
            .replace(/%state/, state);
    } else {
        window.location.href = '<?php echo $this->getFailureUrl(); ?>';
    }
//]]></script>
