<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php echo $this->__($this->getMethod()->getTitle()); ?><br />
<?php if ($this->getInfo()->getAdditionalInformation('amazon_order_reference_id')): ?>
    <?php echo $this->__('Amazon Order Reference ID: %s', $this->htmlEscape(
        $this->getInfo()->getAdditionalInformation('amazon_order_reference_id')
    )); ?><br/>
<?php endif; ?>

