<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Exception details'); ?></h4>
    </div>
    <div class="box">
        <table cellspacing="0" class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label><?php echo $this->__('Date'); ?></label></td>
                    <td class="value"><strong><?php echo $this->escapeHtml($this->getTimestamp()); ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo $this->__('Notification type'); ?></label></td>
                    <td class="value"><?php echo $this->escapeHtml($this->getNotificationType()); ?></td>
                </tr>
                <?php if ($txnId = $this->escapeHtml($this->getTransactionId())) : ?>
                    <tr>
                        <td class="label"><label><?php echo $this->__('Transaction ID'); ?></label></td>
                        <td class="value">
                            <?php if ($txnLink = $this->getTransactionLink()) : ?>
                                <?php echo sprintf('<a href="%s">%s</a>', $txnLink, $txnId); ?>
                            <?php else : ?>
                                <?php echo $txnId; ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endif; ?>
                <tr>
                    <td class="label"><label><?php echo $this->__('Response code'); ?></label></td>
                    <td class="value"><?php echo $this->escapeHtml($this->getResponseCode()); ?></td>
                </tr>
                <?php if ($this->getResponseError()) : ?>
                    <tr>
                        <td class="label"><label><?php echo $this->__('Response error'); ?></label></td>
                        <td class="value"><?php echo $this->escapeHtml($this->getResponseError()); ?></td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
    <?php if ($this->getMessageXml()) : ?>
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Extracted XML message'); ?></h4>
        </div>
        <div class="box box-code">
            <pre><code class="language-markup"><?php echo $this->escapeHtml($this->getMessageXml()); ?></code></pre>
        </div>
    <?php endif; ?>
    <?php if ($this->getRequestBody()) : ?>
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Request Body'); ?></h4>
        </div>
        <div class="box box-code">
            <pre><code class="language-javascript"><?php
                    echo $this->escapeHtml($this->getRequestBody()); ?></code></pre>
        </div>
    <?php endif; ?>
    <?php if ($this->getRequestHeaders()) : ?>
        <div class="entry-edit-head">
            <h4><?php echo $this->__('Request Headers'); ?></h4>
        </div>
        <div class="box box-code">
            <pre><code class="language-http"><?php echo $this->escapeHtml($this->getRequestHeaders()); ?></code></pre>
        </div>
    <?php endif; ?>
</div>
