<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<ul class="messages">
    <li class="notice-msg">
        <ul>
            <li>
                <span><?php echo $this->__(
                    'Please note that the total amount will be charged as soon as an order is placed.'
                ); ?></span>
            </li>
        </ul>
    </li>
</ul>
