<?php if ($this->isEnabled('product_button')): ?>
<p class="stripexpress-logo paypal-logo" style="display: none;">
    <span class="paypal-or"><?php echo $this->__('-OR-'); ?></span>
    <div id="payment-request-button">&nbsp;</div>
</p>
<script type="text/javascript">
    //<![CDATA[
    var MAGENTO_BASE_URL = '<?php echo $this->jsQuoteEscape(Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true)); ?>';
    Event.observe(document, 'dom:loaded', function () {
        stripeExpress.initStripeExpress('<?php echo $this->getPublishableKey(); ?>', <?php echo json_encode($this->getProductApplePayParams()); ?>, <?php echo json_encode($this->getButtonConfig()); ?>, function (paymentRequest, params, prButton) {
            stripeExpress.initProductWidget(paymentRequest, params, prButton);
        });
    });
    //]]>
</script>
<?php endif; ?>

