<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2017 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2017 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<div class="dashboard">
    <div class="box-amazon-account box-info">
        <div class="box-head">
            <h2><?php echo $this->helper('amazonpayments')->__('Login with Amazon'); ?></h2>
            <?php if ($this->isCustomerConnectedWithAmazon()): ?>
                <a href="<?php echo $this->getUrl('amazonpayments/advanced_login/disconnect'); ?>">
                    <?php echo $this->helper('amazonpayments')->__('Disconnect'); ?>
                </a>
            <?php endif; ?>
        </div>
        <div class="box">
            <div class="box-content">
                <?php // @codingStandardsIgnoreStart ?>
                <?php if ($this->isCustomerConnectedWithAmazon()): ?>
                    <p><?php echo $this->helper('amazonpayments')->__('Currently, you can use your Amazon account to log into your shop account. In order to remove the connection to your Amazon account click on "Disconnect".'); ?></p>
                <?php else: ?>
                    <p>
                        <?php echo $this->helper('amazonpayments')->__('With Amazon Pay, you can use the shipping and payment information stored in your Amazon account to place an order on this website. It\'s a convenient and trusted way to pay that\'s enjoyed by millions of people.'); ?>
                        <?php echo $this->helper('amazonpayments')->__('By selecting Login with Amazon, you will be asked to sign-in securely to your Amazon account without leaving the shop.'); ?>
                    </p>
                <?php endif; ?>
                <?php // @codingStandardsIgnoreEnd ?>
            </div>
            <?php if (!$this->isCustomerConnectedWithAmazon()): ?>
                <div class="buttons">
                    <?php echo $this->getChildHtml('button'); ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
