language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - yes '' | pecl install -f redis
  - wget http://download.redis.io/releases/redis-3.2.11.tar.gz
  - tar -xzf redis-3.2.11.tar.gz
  - make -s -C redis-3.2.11 -j4
  - export PATH=$PATH:$PWD/redis-3.2.11/src/

script:
  - phpunit
