<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2019 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2019 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php /** @var Creativestyle_AmazonPayments_Block_Adminhtml_System_Config_Field_ExpertMode $this */ ?>
<?php
    $inputId = $this->getData('html_id');
    $inputName = $this->getData('name');
    $inputValue = $this->getData('value');
    $linkId = $inputId . '_link';
    $expertLabel = $this->helper('amazonpayments')->__('Expert Mode');
?>
<div class="amazon-payments-expert-mode">
    <a href="#" id="<?php echo $linkId; ?>" class="<?php echo $inputValue ? 'open' : ''; ?>">
        <?php echo $expertLabel; ?>
    </a>
    <input type="hidden" id="<?php echo $inputId; ?>" value="<?php echo $inputValue; ?>" name="<?php echo $inputName; ?>"/>
</div>
<script>
    Event.observe('<?php echo $linkId; ?>', 'click', function (e) {
        e.stop();
        var expertModeInput = document.getElementById('<?php echo $inputId; ?>');
        var expertModeLink = document.getElementById('<?php echo $linkId; ?>');
        var expertModeState = parseInt(expertModeInput.value);
        expertModeInput.value = expertModeState ? 0 : 1;
        expertModeLink.className = expertModeState ? '' : 'open';
        expertModeInput.dispatchEvent(new Event('change'));
    });
</script>
