<?php

/**
 * This file is part of the official Amazon Payments Advanced extension
 * for Magento (c) creativestyle GmbH <amazon@creativestyle.de>
 * All rights reserved
 *
 * Reuse or modification of this source code is not allowed
 * without written permission from creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  Copyright (c) 2014 creativestyle GmbH
 * @author     Marek Zabrowarny / creativestyle GmbH <amazon@creativestyle.de>
 */
?>
<?php echo $this->__($this->getMethod()->getTitle()); ?><br />
<?php if ($this->getInfo()->getAdditionalInformation('amazon_order_reference_id')): ?>
    <?php echo $this->__('Amazon Order Reference ID: <a target="_blank" href="https://sellercentral-europe.amazon.com/hz/me/pmd/payment-details?orderReferenceId=%s">%s</a>', $this->htmlEscape($this->getInfo()->getAdditionalInformation('amazon_order_reference_id')), $this->htmlEscape($this->getInfo()->getAdditionalInformation('amazon_order_reference_id'))) ?><br/>
<?php else: ?>
    <?php echo $this->__('Payment has not been processed yet') ?><br/>
<?php endif; ?>
