<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2019 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2019 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<?php /** @var Creativestyle_AmazonPayments_Block_Login_Button $this */ ?>
<div class="cs-lpa-login amazon-login">
    <h2 class="cs-lpa-login__title">
        <?php echo $this->helper('amazonpayments')->__('Use your Amazon Account') ?>
    </h2>
    <?php // @codingStandardsIgnoreStart ?>
    <p class="cs-lpa-login__description">
        <?php echo $this->helper('amazonpayments')->__('With Amazon Pay, you can use the shipping and payment information stored in your Amazon account to place an order on this website. It\'s a convenient and trusted way to pay that\'s enjoyed by millions of people.'); ?>
        <?php echo $this->helper('amazonpayments')->__('By selecting Login with Amazon, you will be asked to sign-in securely to your Amazon account without leaving the shop.'); ?>
    </p>
    <?php // @codingStandardsIgnoreEnd ?>
    <div class="cs-lpa-login__buttons-set buttons-set">
        <div id="<?php echo $this->getContainerId(); ?>"
             class="cs-lpa-login__button <?php echo $this->getContainerClass(); ?>"></div>
    </div>
</div>
<?php $moveBefore = $this->getMoveBefore(); ?>
<?php if ($moveBefore) : ?>
    <script type="text/javascript">
        if ($('<?php echo $moveBefore; ?>')) {
            $$('div.cs-lpa-login').each(function(element) {
                $('<?php echo $moveBefore; ?>').insert(
                    {before: element.addClassName('cs-lpa-login--moved-before position-before')}
                );
            });
        }
    </script>
<?php endif; ?>
