<?php
/**
 * This file is part of the official Amazon Pay and Login with Amazon extension
 * for Magento 1.x
 *
 * (c) 2014 - 2019 creativestyle GmbH. All Rights reserved
 *
 * Distribution of the derivatives reusing, transforming or being built upon
 * this software, is not allowed without explicit written permission granted
 * by creativestyle GmbH
 *
 * @category   Creativestyle
 * @package    Creativestyle_AmazonPayments
 * @copyright  2014 - 2019 creativestyle GmbH
 * @author     Marek Zabrowarny <ticket@creativestyle.de>
 */
?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('customer.form.register.extra')?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="content">
            <?php // @codingStandardsIgnoreStart ?>
            <p><?php echo $this->__('Please fill in required data that cannot be retrieved from your Amazon account.') ?></p>
            <?php // @codingStandardsIgnoreEnd ?>
        </div>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')
                        ->setFieldNameFormat($this->getFieldNameFormat())->setObject($this->getFormData())
                        ->setForceUseCustomerAttributes(true)->toHtml(); ?>
                </li>
                <?php if ($this->isNewsletterEnabled()) : ?>
                <li class="control">
                    <div class="input-box">
                        <input type="checkbox"
                               name="account[is_subscribed]"
                               title="<?php echo $this->__('Sign Up for Newsletter') ?>"
                               value="1"
                               id="is_subscribed"
                            <?php if ($this->getFormData()->getIsSubscribed()) : ?>
                                checked="checked"
                            <?php endif; ?>
                               class="checkbox" />
                    </div>
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $this->getChildHtml('customer.form.register.newsletter')?>
                </li>
                <?php endif ?>
            <?php $dobBlock = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($dobBlock->isEnabled()) : ?>
                <li><?php echo $dobBlock->setFieldNameFormat($this->getFieldNameFormat())
                        ->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $taxvatBlock = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($taxvatBlock->isEnabled()) : ?>
                <li><?php echo $taxvatBlock->setFieldNameFormat($this->getFieldNameFormat())
                        ->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $genderBlock = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($genderBlock->isEnabled()) : ?>
                <li><?php echo $genderBlock->setFieldNameFormat($this->getFieldNameFormat())
                        ->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <p class="back-link">
                <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"
                   onclick="cancelMatching();"
                   class="back-link">
                    <small>&laquo; </small><?php echo $this->__('Back') ?>
                </a>
            </p>
            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button">
                <span><span><?php echo $this->__('Submit') ?></span></span>
            </button>
            <button type="button" class="button cancel" onclick="cancelMatching();">
                <span><span><?php echo $this->__('Cancel') ?></span></span>
            </button>
        </div>
    </form>
    <script type="text/javascript">
        function cancelMatching() {
            AmazonPayments.logout();
            setLocation('<?php echo $this->escapeUrl($this->getBackUrl()); ?>');
        }

        var dataForm = new VarienForm('form-validate', true);
    </script>
</div>
