<?php
/**
 * Der Modulprogrammierer - Vinai Kopp, Rico Neitzel GbR
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the
 * Der Modulprogrammierer - COMMERCIAL SOFTWARE LICENSE (v1.0) (DMCSL 1.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.der-modulprogrammierer.de/licenses/dmcsl-1.0.html
 *
 *
 * @category   DerModPro
 * @package    DerModPro_BasePricePro
 * @copyright  Copyright (c) 2009 Der Modulprogrammierer - Vinai Kopp, Rico Neitzel GbR
 * @copyright  Copyright (c) 2012 Netresearch GmbH 
 * @license    http://www.der-modulprogrammierer.de/licenses/dmcsl-1.0.html  (DMCSL 1.0)
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php if (Mage::helper('basepricepro')->moduleActive()): ?>

<script type="text/javascript">
//<![CDATA[

if(typeof basePrice.product=='undefined') {
	basePrice.product = new BasePrice.Converter(<?php echo Mage::helper('basepricepro')->getBasePriceConfigJson($_product) ?>);
}

//]]>
</script>
<?php endif; ?>