<?php
/**
 * Der Modulprogrammierer - Vinai Kopp, Rico Neitzel GbR
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the
 * Der Modulprogrammierer - COMMERCIAL SOFTWARE LICENSE (v1.0) (DMCSL 1.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.der-modulprogrammierer.de/licenses/dmcsl-1.0.html
 *
 *
 * @category   DerModPro
 * @package    DerModPro_BasePricePro
 * @copyright  Copyright (c) 2009 Der Modulprogrammierer - Vinai Kopp, Rico Neitzel GbR
 * @copyright  Copyright (c) 2012 Netresearch GmbH 
 * @license    http://www.der-modulprogrammierer.de/licenses/dmcsl-1.0.html  (DMCSL 1.0)
 */

/**
 * Set up the JS environment so the scripts access baseprice information
 * 
 * @category   DerModPro
 * @package    DerModPro_BasePricePro
 * @author     Vinai Kopp <vinai@der-modulprogrammierer.de>
 * @see        Mage_Core_Block_Template
 */
?>
<?php if (Mage::helper('basepricepro')->moduleActive()): ?>
<script type="text/javascript">
//<![CDATA[
if(typeof basePrice=='undefined') {
    var basePrice = {};
}
basePrice.format = '<?php echo addslashes($this->__(Mage::helper('basepricepro')->getConfig('frontend_label'))) ?>';
basePrice.inclTax = <?php echo Mage::helper('basepricepro')->getConfig('base_price_incl_tax') ? 'true' : 'false' ?>;
//]]>
</script>
<?php endif; ?>
